[17/Jan/2025 17:36:58] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[17/Jan/2025 17:40:53] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[17/Jan/2025 17:40:58] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[17/Jan/2025 17:41:08] WARNING [django.request:248] Not Found: /
[17/Jan/2025 17:44:00] INFO [campaign.views:126] Received request to list all user campaigns
[17/Jan/2025 17:44:01] INFO [campaign.views:130] Successfully retrieved 0 campaigns
[17/Jan/2025 17:44:24] INFO [campaign.views:83] Received request to create new user campaign
[17/Jan/2025 17:44:24] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[17/Jan/2025 17:44:24] INFO [campaign.views:32] User 10 confirmed as superadmin
[17/Jan/2025 17:44:24] ERROR [django.request:248] Internal Server Error: /campaign/api/campaigns/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 96, in create
    if serializer.is_valid():
       ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\serializers.py", line 223, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\serializers.py", line 442, in run_validation
    value = self.to_internal_value(data)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\serializers.py", line 495, in to_internal_value
    for field in fields:
                 ^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\serializers.py", line 378, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ~~~~~~~~~^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\serializers.py", line 372, in fields
    for key, value in self.get_fields().items():
                      ~~~~~~~~~~~~~~~^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\serializers.py", line 1078, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\utils\model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
           ^^^^^^^^^^^
AttributeError: type object 'UserCampaign' has no attribute '_meta'
[17/Jan/2025 17:51:44] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[17/Jan/2025 17:51:47] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[17/Jan/2025 17:51:56] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[17/Jan/2025 17:51:59] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[17/Jan/2025 17:52:20] INFO [campaign.views:126] Received request to list all user campaigns
[17/Jan/2025 17:52:20] INFO [campaign.views:130] Successfully retrieved 0 campaigns
[17/Jan/2025 17:52:56] INFO [campaign.views:83] Received request to create new user campaign
[17/Jan/2025 17:52:56] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[17/Jan/2025 17:52:56] INFO [campaign.views:32] User 10 confirmed as superadmin
[17/Jan/2025 17:52:56] DEBUG [campaign.views:99] Creating new campaign with data: {}
[17/Jan/2025 17:52:56] ERROR [campaign.views:117] Failed to create campaign: 'type'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 102, in create
    type=user_campaign_data['type'],
         ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
[17/Jan/2025 17:52:56] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[17/Jan/2025 17:54:46] INFO [campaign.views:83] Received request to create new user campaign
[17/Jan/2025 17:54:46] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[17/Jan/2025 17:54:46] INFO [campaign.views:32] User 10 confirmed as superadmin
[17/Jan/2025 17:54:46] DEBUG [campaign.views:99] Creating new campaign with data: {}
[17/Jan/2025 17:54:46] ERROR [campaign.views:117] Failed to create campaign: 'type'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 102, in create
    type=user_campaign_data['type'],
         ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
[17/Jan/2025 17:54:46] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 10:01:06] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:01:16] WARNING [django.request:248] Not Found: /
[20/Jan/2025 10:01:17] WARNING [django.request:248] Not Found: /favicon.ico
[20/Jan/2025 10:02:31] INFO [campaign.views:126] Received request to list all user campaigns
[20/Jan/2025 10:02:32] INFO [campaign.views:130] Successfully retrieved 0 campaigns
[20/Jan/2025 10:03:53] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 10:03:53] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 10:03:53] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 10:03:53] DEBUG [campaign.views:99] Creating new campaign with data: {}
[20/Jan/2025 10:03:53] ERROR [campaign.views:117] Failed to create campaign: 'type'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 102, in create
    type=user_campaign_data['type'],
         ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
[20/Jan/2025 10:03:53] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 10:07:39] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 10:07:43] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:08:34] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 10:08:34] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 10:08:34] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 10:08:34] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 10:08:34] DEBUG [campaign.views:100] Creating new campaign with data: {}
[20/Jan/2025 10:08:34] ERROR [campaign.views:118] Failed to create campaign: 'type'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 103, in create
    type=user_campaign_data['type'],
         ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
[20/Jan/2025 10:08:34] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 10:12:13] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:12:16] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:12:20] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:12:23] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:13:30] INFO [campaign.views:127] Received request to list all user campaigns
[20/Jan/2025 10:13:30] INFO [campaign.views:131] Successfully retrieved 0 campaigns
[20/Jan/2025 10:13:45] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 10:13:45] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 10:13:45] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 10:13:45] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 10:13:45] DEBUG [campaign.views:100] Creating new campaign with data: {}
[20/Jan/2025 10:13:45] ERROR [campaign.views:118] Failed to create campaign: 'type'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 103, in create
    type=user_campaign_data['type'],
         ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
[20/Jan/2025 10:13:45] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 10:20:57] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 10:21:01] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:21:05] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 10:21:10] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:21:15] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 10:21:19] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:21:26] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 10:21:26] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 10:21:26] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 10:21:26] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 10:21:26] DEBUG [campaign.views:100] Data from serializer: {}
[20/Jan/2025 10:21:26] DEBUG [campaign.views:101] Creating new campaign with data: {}
[20/Jan/2025 10:21:26] ERROR [campaign.views:119] Failed to create campaign: 'type'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 104, in create
    type=user_campaign_data['type'],
         ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
[20/Jan/2025 10:21:26] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 10:29:58] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:30:02] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:30:55] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:30:59] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:31:43] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:31:47] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:31:53] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:31:58] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:32:04] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:32:07] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:32:12] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:32:18] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:36:17] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:36:23] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:36:28] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:36:33] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:36:38] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:36:42] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:42:19] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:42:23] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:42:33] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 10:42:37] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 10:42:43] INFO [campaign.views:128] Received request to list all user campaigns
[20/Jan/2025 10:42:43] INFO [campaign.views:132] Successfully retrieved 0 campaigns
[20/Jan/2025 10:42:56] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 10:42:56] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 10:42:56] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 10:42:56] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 10:42:56] DEBUG [campaign.views:100] Data from serializer: {}
[20/Jan/2025 10:42:56] DEBUG [campaign.views:101] Creating new campaign with data: {}
[20/Jan/2025 10:42:56] ERROR [campaign.views:119] Failed to create campaign: 'type'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 104, in create
    type=user_campaign_data['type'],
         ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
[20/Jan/2025 10:42:56] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 11:01:21] INFO [campaign.views:128] Received request to list all user campaigns
[20/Jan/2025 11:01:21] INFO [campaign.views:132] Successfully retrieved 0 campaigns
[20/Jan/2025 11:01:31] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 11:01:31] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 11:01:31] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 11:01:31] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 11:01:31] DEBUG [campaign.views:100] Data from serializer: {}
[20/Jan/2025 11:01:31] DEBUG [campaign.views:101] Creating new campaign with data: {}
[20/Jan/2025 11:01:31] ERROR [campaign.views:119] Failed to create campaign: 'type'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 104, in create
    type=user_campaign_data['type'],
         ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
[20/Jan/2025 11:01:31] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 11:14:53] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:14:57] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:15:01] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:15:04] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:15:12] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:15:16] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:15:21] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:15:26] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:15:34] INFO [campaign.views:129] Received request to list all user campaigns
[20/Jan/2025 11:15:34] INFO [campaign.views:133] Successfully retrieved 0 campaigns
[20/Jan/2025 11:15:45] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 11:15:45] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 11:15:45] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 11:15:45] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 11:15:45] DEBUG [campaign.views:99] serializer is_valid function returned: True
[20/Jan/2025 11:15:45] DEBUG [campaign.views:101] Data from serializer: {}
[20/Jan/2025 11:15:45] DEBUG [campaign.views:102] Creating new campaign with data: {}
[20/Jan/2025 11:15:45] ERROR [campaign.views:120] Failed to create campaign: 'type'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 105, in create
    type=user_campaign_data['type'],
         ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
[20/Jan/2025 11:15:45] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 11:16:18] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:16:23] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:16:28] INFO [campaign.views:129] Received request to list all user campaigns
[20/Jan/2025 11:16:29] INFO [campaign.views:133] Successfully retrieved 0 campaigns
[20/Jan/2025 11:16:38] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 11:16:38] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 11:16:38] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 11:16:38] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 11:16:38] DEBUG [campaign.views:99] serializer: True
[20/Jan/2025 11:16:38] DEBUG [campaign.views:101] Data from serializer: {}
[20/Jan/2025 11:16:38] DEBUG [campaign.views:102] Creating new campaign with data: {}
[20/Jan/2025 11:16:38] ERROR [campaign.views:120] Failed to create campaign: 'type'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 105, in create
    type=user_campaign_data['type'],
         ~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'type'
[20/Jan/2025 11:16:38] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 11:40:11] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 11:40:14] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:40:19] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 11:40:23] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:40:40] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 11:40:40] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 11:40:40] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 11:40:40] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 11:40:40] DEBUG [campaign.views:99] serializer: UserCampaignSerializer(data={'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}):
[20/Jan/2025 11:40:40] ERROR [campaign.views:120] Failed to create campaign: You must call `.is_valid()` before accessing `.validated_data`.
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 100, in create
    user_campaign_data = serializer.validated_data
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\serializers.py", line 267, in validated_data
    raise AssertionError(msg)
AssertionError: You must call `.is_valid()` before accessing `.validated_data`.
[20/Jan/2025 11:40:40] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 11:42:17] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:42:21] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:42:29] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:42:33] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:42:35] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:42:39] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:43:01] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 11:43:01] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 11:43:01] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 11:43:01] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 11:43:01] DEBUG [campaign.views:100] serializer: UserCampaignSerializer(data={'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}):
[20/Jan/2025 11:43:01] ERROR [campaign.views:121] Failed to create campaign: You must call `.is_valid()` before accessing `.validated_data`.
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 101, in create
    user_campaign_data = serializer.validated_data
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\serializers.py", line 267, in validated_data
    raise AssertionError(msg)
AssertionError: You must call `.is_valid()` before accessing `.validated_data`.
[20/Jan/2025 11:43:01] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 11:45:47] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:45:51] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:45:56] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:46:00] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:46:04] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:46:08] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:46:17] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:46:20] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:46:25] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:46:29] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:46:36] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:46:40] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:46:49] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:46:52] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:54:08] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:54:12] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:54:19] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:54:23] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:54:29] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:54:33] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:54:36] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:54:39] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:54:56] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 11:55:00] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:55:50] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 11:55:58] WARNING [django.request:248] Not Found: /
[20/Jan/2025 11:56:04] INFO [campaign.views:127] Received request to list all user campaigns
[20/Jan/2025 11:56:04] INFO [campaign.views:131] Successfully retrieved 0 campaigns
[20/Jan/2025 11:56:21] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 11:56:21] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 11:56:21] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 11:56:21] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 11:56:21] DEBUG [campaign.views:101] serializer: UserCampaignSerializer(data={'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}):
[20/Jan/2025 11:56:21] ERROR [campaign.views:122] Failed to create campaign: You must call `.is_valid()` before accessing `.validated_data`.
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 102, in create
    user_campaign_data = serializer.validated_data
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\serializers.py", line 267, in validated_data
    raise AssertionError(msg)
AssertionError: You must call `.is_valid()` before accessing `.validated_data`.
[20/Jan/2025 11:56:21] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 12:05:29] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:05:34] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:05:43] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:05:47] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:05:51] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:05:55] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:07:44] INFO [campaign.views:127] Received request to list all user campaigns
[20/Jan/2025 12:07:44] INFO [campaign.views:131] Successfully retrieved 0 campaigns
[20/Jan/2025 12:07:58] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 12:07:58] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 12:07:58] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 12:07:58] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 12:07:59] ERROR [django.request:248] Internal Server Error: /campaign/api/campaigns/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 97, in create
    if not serializer.is_valid():
           ~~~~~~~~~~~~~~~~~~~^^
  File "F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py", line 19, in is_valid
    self.errors = {}
    ^^^^^^^^^^^
AttributeError: property 'errors' of 'UserCampaignSerializer' object has no setter
[20/Jan/2025 12:09:25] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:09:30] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:09:35] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:09:38] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:10:14] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:10:17] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:10:31] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:10:36] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:11:03] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:11:07] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:11:20] INFO [campaign.views:127] Received request to list all user campaigns
[20/Jan/2025 12:11:20] INFO [campaign.views:131] Successfully retrieved 0 campaigns
[20/Jan/2025 12:11:33] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 12:11:33] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 12:11:33] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 12:11:33] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 12:11:33] DEBUG [campaign.views:101] serializer: UserCampaignSerializer(data={'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}):
[20/Jan/2025 12:11:33] ERROR [campaign.views:122] Failed to create campaign: You must call `.is_valid()` before accessing `.validated_data`.
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 102, in create
    user_campaign_data = serializer.validated_data
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\serializers.py", line 267, in validated_data
    raise AssertionError(msg)
AssertionError: You must call `.is_valid()` before accessing `.validated_data`.
[20/Jan/2025 12:11:33] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 12:13:03] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:13:07] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:13:15] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:13:18] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:13:20] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:13:25] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:13:28] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:13:32] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:13:51] INFO [campaign.views:127] Received request to list all user campaigns
[20/Jan/2025 12:13:51] INFO [campaign.views:131] Successfully retrieved 0 campaigns
[20/Jan/2025 12:14:05] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 12:14:05] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 12:14:05] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 12:14:05] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 12:14:05] DEBUG [campaign.views:101] serializer: UserCampaignSerializer(data={'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}):
[20/Jan/2025 12:14:05] ERROR [campaign.views:122] Failed to create campaign: You must call `.is_valid()` before accessing `.validated_data`.
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 102, in create
    user_campaign_data = serializer.validated_data
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\serializers.py", line 267, in validated_data
    raise AssertionError(msg)
AssertionError: You must call `.is_valid()` before accessing `.validated_data`.
[20/Jan/2025 12:14:05] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 12:42:09] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:42:12] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:42:16] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:42:19] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:45:54] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:45:58] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:46:01] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:46:04] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:46:11] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:46:15] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:46:19] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:46:22] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:46:26] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:46:32] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:46:34] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:46:38] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:46:45] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:46:49] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:46:53] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:46:56] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:47:01] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:47:05] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:47:19] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:47:24] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:50:15] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:50:19] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:50:36] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:50:39] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:50:51] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 12:50:54] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:51:28] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 12:51:28] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 12:51:28] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 12:51:29] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 12:51:29] DEBUG [campaign.views:101] serializer: UserCampaignSerializer(data={'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}):
    id = IntegerField(read_only=True)
    type = CharField(required=True)
    text = CharField(required=True)
    description = CharField(allow_blank=True, required=False)
    status = CharField(default='active', required=False)
    created_at = DateTimeField(read_only=True)
    updated_at = DateTimeField(read_only=True)
    created_by = IntegerField(required=True)
[20/Jan/2025 12:51:29] DEBUG [campaign.views:103] Data from serializer: {'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active', 'created_by': 10}
[20/Jan/2025 12:51:29] DEBUG [campaign.views:104] Creating new campaign with data: {'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active', 'created_by': 10}
[20/Jan/2025 12:51:29] INFO [campaign.views:115] Successfully created new campaign by user 10
[20/Jan/2025 12:51:29] DEBUG [campaign.serializers:29] to_representation output: {'id': 1, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active', 'created_at': datetime.datetime(2025, 1, 20, 12, 51, 29, 69403, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800))), 'updated_at': datetime.datetime(2025, 1, 20, 12, 51, 29, 69403, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800))), 'created_by': 10}
[20/Jan/2025 12:54:59] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 12:55:03] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:55:08] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 12:55:12] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:55:14] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 12:55:17] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:55:26] INFO [campaign.views:128] Received request to list all user campaigns
[20/Jan/2025 12:55:26] INFO [campaign.views:132] Successfully retrieved 1 campaigns
[20/Jan/2025 12:55:26] DEBUG [campaign.serializers:29] to_representation output: {'id': 1, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active', 'created_at': datetime.datetime(2025, 1, 20, 12, 51, 29, 69403, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800))), 'updated_at': datetime.datetime(2025, 1, 20, 12, 51, 29, 69403, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800))), 'created_by': 10}
[20/Jan/2025 12:55:51] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 12:55:51] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 12:55:51] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 12:55:51] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 12:55:51] DEBUG [campaign.views:101] serializer: UserCampaignSerializer(data={'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}):
    id = IntegerField(read_only=True)
    type = CharField(required=True)
    text = CharField(required=True)
    description = CharField(allow_blank=True, required=False)
    status = CharField(default='active', required=False)
    created_at = DateTimeField(read_only=True)
    updated_at = DateTimeField(read_only=True)
    created_by = IntegerField(required=True)
[20/Jan/2025 12:55:51] DEBUG [campaign.views:103] Data from serializer: {'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active', 'created_by': 10}
[20/Jan/2025 12:55:51] DEBUG [campaign.views:104] Creating new campaign with data: {'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active', 'created_by': 10}
[20/Jan/2025 12:55:51] INFO [campaign.views:115] Successfully created new campaign by user 10
[20/Jan/2025 12:55:51] ERROR [campaign.views:123] Failed to create campaign: 'UserCampaignSerializer' object does not support item assignment
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 118, in create
    response_serializer['User_creation']='Success'
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'UserCampaignSerializer' object does not support item assignment
[20/Jan/2025 12:55:51] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[20/Jan/2025 12:56:08] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 12:56:12] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 12:56:19] INFO [campaign.views:83] Received request to create new user campaign
[20/Jan/2025 12:56:19] DEBUG [campaign.views:84] Request data: {'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}
[20/Jan/2025 12:56:19] INFO [campaign.views:27] Checking superadmin status for user_id: 10
[20/Jan/2025 12:56:19] INFO [campaign.views:32] User 10 confirmed as superadmin
[20/Jan/2025 12:56:19] DEBUG [campaign.views:101] serializer: UserCampaignSerializer(data={'created_by': 10, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active'}):
    id = IntegerField(read_only=True)
    type = CharField(required=True)
    text = CharField(required=True)
    description = CharField(allow_blank=True, required=False)
    status = CharField(default='active', required=False)
    created_at = DateTimeField(read_only=True)
    updated_at = DateTimeField(read_only=True)
    created_by = IntegerField(required=True)
[20/Jan/2025 12:56:19] DEBUG [campaign.views:103] Data from serializer: {'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active', 'created_by': 10}
[20/Jan/2025 12:56:19] DEBUG [campaign.views:104] Creating new campaign with data: {'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active', 'created_by': 10}
[20/Jan/2025 12:56:19] INFO [campaign.views:115] Successfully created new campaign by user 10
[20/Jan/2025 12:56:19] DEBUG [campaign.serializers:29] to_representation output: {'id': 3, 'type': 'email', 'text': 'Sample campaign text', 'description': 'Sample campaign description', 'status': 'active', 'created_at': datetime.datetime(2025, 1, 20, 12, 56, 19, 749768, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800))), 'updated_at': datetime.datetime(2025, 1, 20, 12, 56, 19, 749768, tzinfo=datetime.timezone(datetime.timedelta(seconds=19800))), 'created_by': 10}
[20/Jan/2025 14:14:20] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\models.py changed, reloading.
[20/Jan/2025 14:14:24] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:21:06] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 14:21:10] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:21:28] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 14:21:32] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:21:34] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 14:21:38] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:21:46] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 14:21:50] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:21:57] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[20/Jan/2025 14:22:01] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:22:27] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:22:31] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:22:44] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:22:47] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:22:52] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:22:55] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:23:00] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:23:03] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:23:06] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:23:09] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:23:23] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:23:26] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:23:31] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:23:34] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:23:40] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:23:43] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:24:09] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:24:12] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:40:20] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:40:24] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:40:27] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:40:31] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:40:34] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:40:38] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:40:41] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:40:45] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:41:05] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:41:08] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:41:13] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:41:18] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:41:23] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:41:27] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:42:01] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:42:05] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:42:09] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:42:12] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:42:27] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:42:30] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:43:04] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:43:07] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:43:12] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:43:15] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:43:19] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:43:22] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:45:40] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:45:44] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:45:49] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:45:52] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:46:11] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[20/Jan/2025 14:47:00] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 14:47:00] ERROR [django.request:248] Internal Server Error: /campaign/api/send_email/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 52, in create
    campaign = session.query(user_campaign).filter(id==serializer.validated_data['campaign_id'], user_campaign.status=="pending")
                             ^^^^^^^^^^^^^
NameError: name 'user_campaign' is not defined. Did you mean: 'UserCampaign'?
[20/Jan/2025 14:47:54] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:47:58] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:48:02] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:48:06] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:48:10] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:48:14] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:48:18] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[20/Jan/2025 14:48:44] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 14:48:44] ERROR [django.request:248] Internal Server Error: /campaign/api/send_email/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 55, in create
    subject = campaign.subject
              ^^^^^^^^^^^^^^^^
AttributeError: 'Query' object has no attribute 'subject'
[20/Jan/2025 14:49:07] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:49:11] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:49:18] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:49:21] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:49:26] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[20/Jan/2025 14:50:03] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 14:50:03] ERROR [django.request:248] Internal Server Error: /campaign/api/send_email/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 55, in create
    subject = campaign.title
              ^^^^^^^^^^^^^^
AttributeError: 'Query' object has no attribute 'title'
[20/Jan/2025 14:50:15] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:50:19] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:50:23] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:50:26] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:50:33] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:50:37] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:50:41] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:50:45] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:50:49] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[20/Jan/2025 14:51:15] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 14:51:15] INFO [campaign.views:54] campaign object that we got: SELECT user_campaign.id AS user_campaign_id, user_campaign.type AS user_campaign_type, user_campaign.text AS user_campaign_text, user_campaign.description AS user_campaign_description, user_campaign.status AS user_campaign_status, user_campaign.created_at AS user_campaign_created_at, user_campaign.updated_at AS user_campaign_updated_at, user_campaign.created_by AS user_campaign_created_by 
FROM user_campaign 
WHERE user_campaign.id = %(id_1)s AND user_campaign.status = %(status_1)s
[20/Jan/2025 14:51:15] ERROR [django.request:248] Internal Server Error: /campaign/api/send_email/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 56, in create
    subject = campaign.title
              ^^^^^^^^^^^^^^
AttributeError: 'Query' object has no attribute 'title'
[20/Jan/2025 14:52:19] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:52:23] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:52:30] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[20/Jan/2025 14:52:35] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 14:52:35] INFO [campaign.views:54] campaign object that we got: SELECT user_campaign.id AS user_campaign_id, user_campaign.type AS user_campaign_type, user_campaign.text AS user_campaign_text, user_campaign.description AS user_campaign_description, user_campaign.status AS user_campaign_status, user_campaign.created_at AS user_campaign_created_at, user_campaign.updated_at AS user_campaign_updated_at, user_campaign.created_by AS user_campaign_created_by 
FROM user_campaign 
WHERE user_campaign.id = %(id_1)s AND user_campaign.status = %(status_1)s
[20/Jan/2025 14:52:35] ERROR [django.request:248] Internal Server Error: /campaign/api/send_email/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\viewsets.py", line 124, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 56, in create
    subject = campaign.text
              ^^^^^^^^^^^^^
AttributeError: 'Query' object has no attribute 'text'
[20/Jan/2025 14:53:54] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:53:59] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:54:04] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[20/Jan/2025 14:54:12] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 14:54:13] INFO [campaign.views:54] campaign object that we got: <campaign.models.UserCampaign object at 0x000001F3F3431FD0>
[20/Jan/2025 14:54:13] DEBUG [campaign.views:59] Querying users with 'user' role
[20/Jan/2025 14:54:13] INFO [campaign.views:65] Attempting to send email to 1 users
[20/Jan/2025 14:54:13] ERROR [campaign.views:72] Failed to send email: name 'from_email' is not defined
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 66, in create
    send_mail(subject, message, from_email, users_list)
                                ^^^^^^^^^^
NameError: name 'from_email' is not defined
[20/Jan/2025 14:54:13] ERROR [django.request:248] Internal Server Error: /campaign/api/send_email/
[20/Jan/2025 14:54:52] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:54:57] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:54:58] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[20/Jan/2025 14:55:05] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 14:55:05] INFO [campaign.views:54] campaign object that we got: <campaign.models.UserCampaign object at 0x000002A147A19FD0>
[20/Jan/2025 14:55:05] DEBUG [campaign.views:59] Querying users with 'user' role
[20/Jan/2025 14:55:05] INFO [campaign.views:65] Attempting to send email to 1 users
[20/Jan/2025 14:55:05] ERROR [campaign.views:72] Failed to send email: send_mail() missing 1 required positional argument: 'recipient_list'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 66, in create
    send_mail(subject, message, users_list)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: send_mail() missing 1 required positional argument: 'recipient_list'
[20/Jan/2025 14:55:05] ERROR [django.request:248] Internal Server Error: /campaign/api/send_email/
[20/Jan/2025 14:55:32] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:55:36] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:55:40] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:55:43] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:55:48] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[20/Jan/2025 14:55:53] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 14:55:53] INFO [campaign.views:54] campaign object that we got: <campaign.models.UserCampaign object at 0x0000020DF3ABDFD0>
[20/Jan/2025 14:55:53] DEBUG [campaign.views:59] Querying users with 'user' role
[20/Jan/2025 14:55:53] INFO [campaign.views:65] Attempting to send email to 1 users
[20/Jan/2025 14:55:53] ERROR [campaign.views:72] Failed to send email: send_mail() missing 1 required positional argument: 'from_email'
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 66, in create
    send_mail(subject=subject, message=message, recipient_list=users_list)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: send_mail() missing 1 required positional argument: 'from_email'
[20/Jan/2025 14:55:53] ERROR [django.request:248] Internal Server Error: /campaign/api/send_email/
[20/Jan/2025 14:57:07] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:57:11] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:57:15] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:57:20] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:57:22] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 14:57:25] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 14:57:36] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[20/Jan/2025 14:57:43] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 14:57:43] INFO [campaign.views:54] campaign object that we got: <campaign.models.UserCampaign object at 0x0000013540FADFD0>
[20/Jan/2025 14:57:43] DEBUG [campaign.views:59] Querying users with 'user' role
[20/Jan/2025 14:57:43] INFO [campaign.views:65] Attempting to send email to 1 users
[20/Jan/2025 14:57:46] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 14:57:46] INFO [campaign.views:54] campaign object that we got: <campaign.models.UserCampaign object at 0x0000013540FADFD0>
[20/Jan/2025 14:57:46] DEBUG [campaign.views:59] Querying users with 'user' role
[20/Jan/2025 14:57:46] INFO [campaign.views:65] Attempting to send email to 1 users
[20/Jan/2025 14:57:48] INFO [campaign.views:67] Email sent successfully
[20/Jan/2025 14:57:50] INFO [campaign.views:67] Email sent successfully
[20/Jan/2025 15:01:50] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 15:01:55] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 15:02:00] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 15:02:05] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 15:02:12] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 15:02:16] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 15:02:27] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 15:02:27] INFO [campaign.views:54] campaign object that we got: <campaign.models.UserCampaign object at 0x00000195D429B770>
[20/Jan/2025 15:02:27] DEBUG [campaign.views:59] Querying users with 'user' role
[20/Jan/2025 15:02:27] INFO [campaign.views:65] Attempting to send email to 1 users
[20/Jan/2025 15:02:27] INFO [campaign.views:66] Recipient list is <QuerySet ['njulkushwaha@gmail.com']>
[20/Jan/2025 15:02:32] INFO [campaign.views:68] Email sent successfully
[20/Jan/2025 15:08:41] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 15:08:45] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 15:08:50] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 15:08:54] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 15:08:58] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 15:09:01] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 15:09:05] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 15:09:10] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 15:10:15] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 15:10:19] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 15:10:29] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 15:10:32] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 15:10:39] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 15:10:42] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 15:10:46] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[20/Jan/2025 15:10:49] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[20/Jan/2025 15:11:04] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[20/Jan/2025 15:11:19] INFO [campaign.views:48] Received request to send test email
[20/Jan/2025 15:11:19] DEBUG [campaign.views:53] Checking if sender with ID 10 is an admin
[20/Jan/2025 15:11:19] WARNING [campaign.views:57] Sender with ID 10 is not authorized to send emails
[20/Jan/2025 15:11:19] WARNING [django.request:248] Forbidden: /campaign/api/send_email/
[21/Jan/2025 12:49:34] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:49:38] WARNING [django.request:248] Not Found: /
[21/Jan/2025 12:55:04] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:55:08] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:55:12] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:55:16] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:55:21] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:55:24] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:55:46] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:55:50] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:55:54] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:55:57] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:56:02] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:56:07] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:56:10] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:56:13] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:56:16] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:56:19] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:56:25] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:56:29] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:56:33] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:56:37] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:56:41] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:56:44] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:57:04] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\serializers.py changed, reloading.
[21/Jan/2025 12:57:08] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:57:14] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\serializers.py changed, reloading.
[21/Jan/2025 12:57:17] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:57:22] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\serializers.py changed, reloading.
[21/Jan/2025 12:57:26] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:57:36] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\serializers.py changed, reloading.
[21/Jan/2025 12:57:39] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:58:13] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\serializers.py changed, reloading.
[21/Jan/2025 12:58:17] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:58:40] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:58:43] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:59:01] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:59:04] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:59:11] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:59:14] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 12:59:21] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 12:59:25] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 13:00:43] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 13:00:47] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 13:00:53] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 13:00:56] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 13:01:01] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 13:01:04] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 13:01:09] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 13:01:12] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 13:01:16] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 13:01:21] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 13:01:25] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 13:01:28] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 13:01:41] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 13:01:44] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 13:01:47] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 13:01:51] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:04:52] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:04:56] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:05:04] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:05:15] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:05:26] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:05:39] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:05:48] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:05:54] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:05:59] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:06:03] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:06:07] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:06:12] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:06:15] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:06:19] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:06:25] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:06:30] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:06:34] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:06:38] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:06:46] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:06:50] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:06:52] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:06:55] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:07:15] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:07:18] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:10:59] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:11:10] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:11:15] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:11:19] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:11:23] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:11:27] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:11:38] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:11:43] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:11:47] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:11:50] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:11:56] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:12:00] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:12:05] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:12:08] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:12:14] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:12:18] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:12:25] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:12:29] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:12:33] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:12:37] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:12:42] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:12:46] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:12:48] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:12:52] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:13:27] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\urls.py changed, reloading.
[21/Jan/2025 14:13:30] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:13:33] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\urls.py changed, reloading.
[21/Jan/2025 14:13:37] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:14:50] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:17:22] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:17:29] WARNING [django.request:248] Not Found: /users/api/extended_user/
[21/Jan/2025 14:17:33] WARNING [django.request:248] Not Found: /users/api/extended_user/
[21/Jan/2025 14:23:09] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:23:13] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:23:17] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:23:20] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:23:25] ERROR [django.request:248] Internal Server Error: /users/api/login/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\renderers.py", line 727, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\renderers.py", line 683, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\renderers.py", line 413, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\S\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\S\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\S\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type RefreshToken is not JSON serializable
[21/Jan/2025 14:23:35] ERROR [django.request:248] Internal Server Error: /users/api/login/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\renderers.py", line 727, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\renderers.py", line 683, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\renderers.py", line 413, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
        data, cls=self.encoder_class,
        indent=indent, ensure_ascii=self.ensure_ascii,
        allow_nan=not self.strict, separators=separators
    )
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\S\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "C:\Users\S\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\S\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
           ~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type RefreshToken is not JSON serializable
[21/Jan/2025 14:23:50] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:23:53] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:23:58] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:24:01] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:31:46] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\urls.py changed, reloading.
[21/Jan/2025 14:31:50] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:37:17] WARNING [django.request:248] Not Found: /users/
[21/Jan/2025 14:37:28] WARNING [django.request:248] Method Not Allowed: /users/api/login/
[21/Jan/2025 14:40:33] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:40:37] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:40:41] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 14:40:44] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:41:57] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 14:41:58] WARNING [extended_user.views:106] Failed login attempt for user: njul
[21/Jan/2025 14:41:58] WARNING [django.request:248] Unauthorized: /users/api/login/
[21/Jan/2025 14:51:52] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\lightbulb\settings.py changed, reloading.
[21/Jan/2025 14:51:57] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:54:53] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 14:54:57] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:55:03] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 14:55:07] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:55:16] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 14:55:20] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:55:22] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 14:55:26] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 14:55:31] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 14:55:37] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:00:19] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:00:23] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:00:26] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:00:29] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:04:57] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:05:01] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:05:04] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:05:08] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:05:11] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:05:14] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:05:39] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:05:43] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:05:53] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:05:56] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:06:48] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:06:52] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:09:39] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:09:43] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:21:25] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:21:29] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:22:43] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:23:44] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:23:47] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:23:51] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 15:23:54] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:24:15] WARNING [django.request:248] Not Found: /
[21/Jan/2025 15:24:22] WARNING [django.request:248] Unauthorized: /campaign/api/
[21/Jan/2025 15:24:47] WARNING [django.request:248] Not Found: /campaign/
[21/Jan/2025 15:24:53] WARNING [django.request:248] Unauthorized: /campaign/api/
[21/Jan/2025 15:25:30] WARNING [django.request:248] Unauthorized: /campaign/api/send_email/
[21/Jan/2025 15:26:12] WARNING [django.request:248] Unauthorized: /campaign/api/
[21/Jan/2025 15:27:54] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\lightbulb\settings.py changed, reloading.
[21/Jan/2025 15:27:58] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:28:31] WARNING [django.request:248] Unauthorized: /campaign/api/campaigns/
[21/Jan/2025 15:28:37] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[21/Jan/2025 15:28:43] WARNING [django.request:248] Unauthorized: /campaign/api/campaigns/
[21/Jan/2025 15:31:30] WARNING [django.request:248] Method Not Allowed: /campaign/api/send_email/
[21/Jan/2025 15:37:54] WARNING [django.request:248] Unauthorized: /campaign/api/campaigns/
[21/Jan/2025 15:39:19] WARNING [django.request:248] Unauthorized: /campaign/api/campaigns/
[21/Jan/2025 15:39:37] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 15:39:39] INFO [extended_user.views:99] Successful login for user: njul
[21/Jan/2025 15:40:13] WARNING [django.request:248] Unauthorized: /campaign/api/campaigns/
[21/Jan/2025 15:40:33] INFO [campaign.views:28] Checking superadmin status for user_id: 1
[21/Jan/2025 15:40:33] WARNING [campaign.views:35] User 1 is not a superadmin or doesn't exist
[21/Jan/2025 15:40:33] WARNING [django.request:248] Forbidden: /campaign/api/campaigns/
[21/Jan/2025 15:53:39] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 15:53:41] WARNING [extended_user.views:106] Failed login attempt for user: njul11
[21/Jan/2025 15:53:41] WARNING [django.request:248] Unauthorized: /users/api/login/
[21/Jan/2025 15:58:38] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\serializers.py changed, reloading.
[21/Jan/2025 15:58:42] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 15:59:11] INFO [extended_user.views:38] Fetching all extended users
[21/Jan/2025 15:59:11] INFO [extended_user.views:43] Successfully retrieved 5 extended users
[21/Jan/2025 16:00:51] INFO [extended_user.views:50] Attempting to create new user and extended user
[21/Jan/2025 16:00:52] INFO [extended_user.views:57] Created Django user with ID: 11
[21/Jan/2025 16:00:52] ERROR [extended_user.views:75] Error creating extended user: 'role'
[21/Jan/2025 16:00:53] INFO [extended_user.views:81] Rolled back Django user creation for ID: None
[21/Jan/2025 16:00:53] ERROR [django.request:248] Internal Server Error: /users/api/signup/
[21/Jan/2025 16:02:48] INFO [extended_user.views:50] Attempting to create new user and extended user
[21/Jan/2025 16:02:50] INFO [extended_user.views:57] Created Django user with ID: 12
[21/Jan/2025 16:02:50] INFO [extended_user.views:67] Created extended user with ID: 12
[21/Jan/2025 16:03:13] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 16:03:15] INFO [extended_user.views:99] Successful login for user: anjul
[21/Jan/2025 16:05:33] INFO [campaign.views:28] Checking superadmin status for user_id: 12
[21/Jan/2025 16:05:34] INFO [campaign.views:33] User 12 confirmed as superadmin
[21/Jan/2025 16:05:34] INFO [campaign.views:109] Received request to create new user campaign
[21/Jan/2025 16:05:34] DEBUG [campaign.views:110] Request data: {'type': 'Email', 'text': 'Welcome to our new product launch!', 'description': 'This campaign is to introduce our latest product to our users.', 'status': 'active'}
[21/Jan/2025 16:05:34] WARNING [campaign.views:115] Invalid campaign data provided: {'created_by': [ErrorDetail(string='This field is required.', code='required')]}
[21/Jan/2025 16:05:34] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[21/Jan/2025 16:06:00] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[21/Jan/2025 16:06:03] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:06:15] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[21/Jan/2025 16:06:19] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:08:50] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:08:53] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:09:05] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:09:09] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:09:14] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:09:18] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:09:21] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:09:25] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:09:32] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:09:35] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:09:40] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:09:43] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:10:34] WARNING [django.request:248] Unauthorized: /campaign/api/campaigns/
[21/Jan/2025 16:10:53] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 16:10:55] INFO [extended_user.views:99] Successful login for user: anjul
[21/Jan/2025 16:11:24] INFO [campaign.views:28] Checking superadmin status for user_id: 12
[21/Jan/2025 16:11:24] INFO [campaign.views:33] User 12 confirmed as superadmin
[21/Jan/2025 16:11:24] INFO [campaign.views:109] Received request to create new user campaign
[21/Jan/2025 16:11:24] DEBUG [campaign.views:110] Request data: {'type': 'Email', 'text': 'Welcome to our new product launch!', 'description': 'This campaign is to introduce our latest product to our users.', 'status': 'active'}
[21/Jan/2025 16:11:24] DEBUG [campaign.views:118] serializer: UserCampaignSerializer(data={'type': 'Email', 'text': 'Welcome to our new product launch!', 'description': 'This campaign is to introduce our latest product to our users.', 'status': 'active', 'created_by': 12}):
    type = CharField(required=True)
    text = CharField(required=True)
    description = CharField(allow_blank=True, required=False)
    status = CharField(default='active', required=False)
    created_at = DateTimeField(read_only=True)
    updated_at = DateTimeField(read_only=True)
    created_by = IntegerField(required=True)
[21/Jan/2025 16:11:24] DEBUG [campaign.views:120] Data from serializer: {'type': 'Email', 'text': 'Welcome to our new product launch!', 'description': 'This campaign is to introduce our latest product to our users.', 'status': 'active', 'created_by': 12}
[21/Jan/2025 16:11:24] DEBUG [campaign.views:121] Creating new campaign with data: {'type': 'Email', 'text': 'Welcome to our new product launch!', 'description': 'This campaign is to introduce our latest product to our users.', 'status': 'active', 'created_by': 12}
[21/Jan/2025 16:11:24] ERROR [campaign.views:139] Failed to create campaign: name 'user_id' is not defined
Traceback (most recent call last):
  File "F:\PROGRAMMING\django\ILP\backend\campaign\views.py", line 132, in create
    logger.info(f"Successfully created new campaign by user {user_id}")
                                                             ^^^^^^^
NameError: name 'user_id' is not defined
[21/Jan/2025 16:11:24] WARNING [django.request:248] Bad Request: /campaign/api/campaigns/
[21/Jan/2025 16:11:59] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:12:03] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:25:05] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:25:09] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:25:14] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:25:19] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:25:26] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:25:29] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:25:50] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:25:55] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:25:59] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:26:04] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:26:09] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:26:13] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:26:28] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:26:32] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:26:42] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:26:46] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:26:50] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:26:54] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:26:58] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:27:01] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:27:06] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:27:10] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:27:17] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:27:21] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:27:25] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:27:29] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:27:33] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:27:36] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:28:01] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[21/Jan/2025 16:28:05] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:28:13] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:28:17] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:28:26] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:28:30] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:28:37] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:28:41] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:29:48] WARNING [django.request:248] Unauthorized: /campaign/api/send_email/
[21/Jan/2025 16:33:15] INFO [extended_user.views:38] Fetching all extended users
[21/Jan/2025 16:33:15] INFO [extended_user.views:43] Successfully retrieved 6 extended users
[21/Jan/2025 16:34:24] INFO [extended_user.views:50] Attempting to create new user and extended user
[21/Jan/2025 16:34:26] INFO [extended_user.views:57] Created Django user with ID: 13
[21/Jan/2025 16:34:26] INFO [extended_user.views:67] Created extended user with ID: 13
[21/Jan/2025 16:34:53] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 16:34:55] INFO [extended_user.views:99] Successful login for user: test_admin
[21/Jan/2025 16:36:07] INFO [campaign.views:28] Checking superadmin status for user_id: 13
[21/Jan/2025 16:36:07] WARNING [campaign.views:35] User 13 is not a superadmin or doesn't exist
[21/Jan/2025 16:36:07] WARNING [django.request:248] Forbidden: /campaign/api/send_email/
[21/Jan/2025 16:37:03] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\views.py changed, reloading.
[21/Jan/2025 16:37:07] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:37:20] INFO [campaign.views:49] Checking superadmin status for user_id: 13
[21/Jan/2025 16:37:20] INFO [campaign.views:54] User 13 confirmed as admin
[21/Jan/2025 16:37:20] INFO [campaign.views:95] Received request to send test email
[21/Jan/2025 16:37:20] WARNING [django.request:248] Unsupported Media Type: /campaign/api/send_email/
[21/Jan/2025 16:39:22] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:39:29] INFO [campaign.views:49] Checking superadmin status for user_id: 13
[21/Jan/2025 16:39:29] INFO [campaign.views:54] User 13 confirmed as admin
[21/Jan/2025 16:39:29] INFO [campaign.views:95] Received request to send test email
[21/Jan/2025 16:39:29] INFO [campaign.views:100] campaign object that we got: None
[21/Jan/2025 16:39:29] DEBUG [campaign.views:105] Querying users with 'user' role
[21/Jan/2025 16:39:29] INFO [campaign.views:111] Attempting to send email to 1 users
[21/Jan/2025 16:39:29] INFO [campaign.views:112] Recipient list is <QuerySet ['njulkushwaha@gmail.com']>
[21/Jan/2025 16:39:34] INFO [campaign.views:114] Email sent successfully
[21/Jan/2025 16:41:30] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\campaign\serializers.py changed, reloading.
[21/Jan/2025 16:41:33] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 16:41:41] WARNING [django.request:248] Unauthorized: /campaign/api/send_email/
[21/Jan/2025 16:41:49] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 16:41:51] INFO [extended_user.views:99] Successful login for user: test_admin
[21/Jan/2025 16:42:27] INFO [campaign.views:49] Checking superadmin status for user_id: 13
[21/Jan/2025 16:42:27] INFO [campaign.views:54] User 13 confirmed as admin
[21/Jan/2025 16:42:27] INFO [campaign.views:95] Received request to send test email
[21/Jan/2025 16:42:27] INFO [campaign.views:100] campaign object that we got: <campaign.models.UserCampaign object at 0x00000214F13752B0>
[21/Jan/2025 16:42:27] DEBUG [campaign.views:105] Querying users with 'user' role
[21/Jan/2025 16:42:27] INFO [campaign.views:111] Attempting to send email to 1 users
[21/Jan/2025 16:42:27] INFO [campaign.views:112] Recipient list is <QuerySet ['njulkushwaha@gmail.com']>
[21/Jan/2025 16:42:32] INFO [campaign.views:114] Email sent successfully
[21/Jan/2025 16:46:29] INFO [campaign.views:49] Checking superadmin status for user_id: 13
[21/Jan/2025 16:46:29] INFO [campaign.views:54] User 13 confirmed as admin
[21/Jan/2025 16:46:29] INFO [campaign.views:95] Received request to send test email
[21/Jan/2025 16:46:29] INFO [campaign.views:100] campaign object that we got: <campaign.models.UserCampaign object at 0x00000214F1373250>
[21/Jan/2025 16:46:29] DEBUG [campaign.views:105] Querying users with 'user' role
[21/Jan/2025 16:46:29] INFO [campaign.views:111] Attempting to send email to 1 users
[21/Jan/2025 16:46:29] INFO [campaign.views:112] Recipient list is <QuerySet ['njulkushwaha@gmail.com']>
[21/Jan/2025 16:46:33] INFO [campaign.views:114] Email sent successfully
[21/Jan/2025 17:15:12] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\lightbulb\settings.py changed, reloading.
[21/Jan/2025 17:15:16] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:15:21] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\lightbulb\settings.py changed, reloading.
[21/Jan/2025 17:15:26] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:15:39] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\lightbulb\settings.py changed, reloading.
[21/Jan/2025 17:15:44] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:15:50] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\lightbulb\settings.py changed, reloading.
[21/Jan/2025 17:15:54] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:16:05] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\lightbulb\settings.py changed, reloading.
[21/Jan/2025 17:16:09] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:23:23] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\lightbulb\settings.py changed, reloading.
[21/Jan/2025 17:23:27] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:25:32] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:25:42] ERROR [django.request:248] Internal Server Error: /users/api/login
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\utils\deprecation.py", line 131, in __call__
    response = self.process_response(request, response)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
    ...<9 lines>...
    )
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/users/api/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
[21/Jan/2025 17:26:43] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 17:26:45] WARNING [extended_user.views:106] Failed login attempt for user: anjul
[21/Jan/2025 17:26:45] WARNING [django.request:248] Unauthorized: /users/api/login/
[21/Jan/2025 17:27:45] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 17:27:46] INFO [extended_user.views:99] Successful login for user: test_admin
[21/Jan/2025 17:33:53] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:33:57] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:34:08] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:34:12] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:34:16] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:34:20] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:34:25] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:34:28] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:34:49] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:34:53] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:34:57] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:35:01] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:35:16] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:35:20] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:35:24] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:35:28] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:36:09] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:36:12] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:36:16] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:36:21] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:36:28] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:36:32] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:36:35] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:36:40] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:36:57] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 17:36:59] INFO [extended_user.views:99] Successful login for user: test_admin
[21/Jan/2025 17:36:59] ERROR [django.request:248] Internal Server Error: /users/api/login/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\PROGRAMMING\django\ILP\backend\extended_user\views.py", line 100, in post
    user_role = session.query(extended_user).filter_by(extended_user.id==user.id)
TypeError: Query.filter_by() takes 1 positional argument but 2 were given
[21/Jan/2025 17:37:17] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:37:22] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:37:30] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 17:37:32] INFO [extended_user.views:99] Successful login for user: test_admin
[21/Jan/2025 17:37:32] ERROR [django.request:248] Internal Server Error: /users/api/login/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\PROGRAMMING\django\ILP\backend\extended_user\views.py", line 100, in post
    user_role = session.query(extended_user).filter_by(id==user.id)
TypeError: Query.filter_by() takes 1 positional argument but 2 were given
[21/Jan/2025 17:37:47] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:37:51] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
[21/Jan/2025 17:38:13] INFO [extended_user.views:89] Processing login request
[21/Jan/2025 17:38:15] INFO [extended_user.views:99] Successful login for user: test_admin
[21/Jan/2025 17:38:15] ERROR [django.request:248] Internal Server Error: /users/api/login/
Traceback (most recent call last):
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\S\.virtualenvs\backend-xHKri2Ze\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "F:\PROGRAMMING\django\ILP\backend\extended_user\views.py", line 103, in post
    role = user_role.role
           ^^^^^^^^^^^^^^
AttributeError: 'Query' object has no attribute 'role'
[21/Jan/2025 17:38:55] INFO [django.utils.autoreload:266] F:\PROGRAMMING\django\ILP\backend\extended_user\views.py changed, reloading.
[21/Jan/2025 17:38:59] INFO [django.utils.autoreload:668] Watching for file changes with StatReloader
